properties:
    connection.string: "host=localhost port=5432 dbname=roowix user=postgres password=12345"

routes:
    /api/orders: Roowix\Controller\OrdersController
    /api/orders/{order_id}: Roowix\Controller\OrdersController
    /api/users/: Roowix\Controller\UsersController
    /api/users/{user_id}: Roowix\Controller\UsersController

services:
    postgres.connection:
        class: Roowix\DB\Connection
        arguments:
            - '%connection.string%'
    orders.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.order'
    orders.controller:
        class: Roowix\Controller\OrdersController
        arguments:
            - '@orders.entity.storage'
    users.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.user'
    users.controller:
        class: Roowix\Controller\UsersController
        arguments:
            - '@users.entity.storage'
