properties:
    connection.string: "host=localhost port=5432 dbname=roowix user=postgres password=12345"

routes:
    /api/users/: '@users.controller'
    /api/users/{user_id}: '@users.controller'
    /api/tasks/: '@tasks.controller'
    /api/tasks/{task_id}: '@tasks.controller'
    /api/tasks/{task_id}/progress: '@tasks.progress.controller'
    /api/progress/: '@progress.controller'
    /api/progress/{task_progress_id}: '@progress.controller'
    /api/tree: '@tree.controller'

services:
    postgres.connection:
        class: Roowix\DB\Connection
        arguments:
            - '%connection.string%'

    users.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.user'
    users.controller:
        class: Roowix\Controller\UsersController
        arguments:
            - '@users.entity.storage'

    tasks.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.task'
    tasks.controller:
        class: Roowix\Controller\TasksController
        arguments:
            - '@tasks.entity.storage'

    progress.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.task_progress'
    progress.controller:
        class: Roowix\Controller\ProgressController
        arguments:
            - '@progress.entity.storage'

    tree.controller:
        class: Roowix\Controller\TreeController
        arguments:
            - '@tasks.entity.storage'
            - '@progress.entity.storage'
            - Roowix\Model\Tree\TreeFactory

    tasks.progress.controller:
        class: Roowix\Controller\TasksProgressController
        arguments:
            - '@progress.entity.storage'
