properties:
    connection.string: "host=localhost port=5432 dbname=roowix user=postgres password=12345"

routes:
    /api/orders: '@orders.controller'
    /api/orders/{id}: '@orders.controller'
    /api/users/: '@users.controller'
    /api/users/{id}: '@users.controller'

services:
    postgres.connection:
        class: Roowix\DB\Connection
        arguments:
            - '%connection.string%'
    orders.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.order'
    orders.controller:
        class: Roowix\Controller\GenericRestController
        arguments:
            - '@orders.entity.storage'
            - Roowix\Model\OrderEntityDescription
    users.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.user'
    users.controller:
        class: Roowix\Controller\GenericRestController
        arguments:
            - '@users.entity.storage'
            - Roowix\Model\UserEntityDescription
