properties:
    connection.string: "host=localhost port=5432 dbname=roowix user=postgres password=12345"

routes:
    /api/users/: '@users.controller'
    /api/users/{user_id}: '@users.controller'
    /api/tasks/: '@tasks.controller'
    /api/tasks/{task_id}: '@tasks.controller'
    /api/tasks/{task_id}/progress: '@tasks.progress.controller'
    /api/progress/: '@progress.controller'
    /api/progress/{task_progress_id}: '@progress.controller'
    /api/tree: '@tree.controller'
    /api/groups: '@groups.controller'
    /api/groups/{group_id}: '@groups.controller'
    /api/groups/{group_id}/users: '@group.users.controller'
    /api/groups/{group_id}/users/{user_id}: '@group.users.controller'

services:
    postgres.connection:
        class: Roowix\DB\Connection
        arguments:
            - '%connection.string%'

    users.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.user'
            - Roowix\Model\Storage\UserEntity
    users.controller:
        class: Roowix\Controller\UsersController
        arguments:
            - '@users.entity.storage'

    tasks.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.task'
            - Roowix\Model\Storage\TaskEntity
    tasks.controller:
        class: Roowix\Controller\TasksController
        arguments:
            - '@tasks.entity.storage'

    progress.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.task_progress'
            - Roowix\Model\Storage\ProgressEntity
    progress.controller:
        class: Roowix\Controller\ProgressController
        arguments:
            - '@progress.entity.storage'

    tree.controller:
        class: Roowix\Controller\TreeController
        arguments:
            - '@tasks.entity.storage'
            - '@progress.entity.storage'
            - Roowix\Model\Tree\TreeFactory

    tasks.progress.controller:
        class: Roowix\Controller\TasksProgressController
        arguments:
            - '@progress.entity.storage'

    groups.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.group'
            - Roowix\Model\Storage\GroupEntity

    group.users.entity.storage:
        class: Roowix\DB\PostgresEntityStorage
        arguments:
            - '@postgres.connection'
            - 'public.group_user'
            - Roowix\Model\Storage\GroupUserEntity

    groups.controller:
        class: Roowix\Controller\GroupsController
        arguments:
            - '@groups.entity.storage'

    group.users.controller:
        class: Roowix\Controller\GroupUsersController
        arguments:
            - '@groups.entity.storage'
            - '@group.users.entity.storage'
